source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view, UserDetailView, UserChangeView,\
    UserChangePasswordView, UserIndexView

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/update', UserChangeView.as_view(), name='user_update'),
    path('<int:pk>/password_change', UserChangePasswordView.as_view(), name='user_change_password'),
    path('users', UserIndexView.as_view(), name='user_index'),
]

app_name = 'accounts'

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace='webapp')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, FileView, FileCreateView, FileUpdateView, FileDeleteView, AddPrivateAccess

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('file/<int:pk>/', FileView.as_view(), name='file_view'),
    path('file/add/', FileCreateView.as_view(), name='file_add'),
    path('file/<int:pk>/update/', FileUpdateView.as_view(), name='file_update'),
    path('file/<int:pk>/delete/', AddPrivateAccess.as_view(), name='file_delete'),

    path('file/add_private_user', AddPrivateAccess.as_view(), name='add_private_access')

    # path('project/<int:pk>/add-review/', ReviewForProductCreateView.as_view(), name='product_review_create'),
    # path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    # path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
    ]

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='User')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Avatar')
    about = models.TextField(max_length=2000, null=True, blank=True, verbose_name='About')
    git_hub = models.URLField(default='', blank=True)

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'

source/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

from accounts.models import Profile


class UserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Password", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm Password", widget=forms.PasswordInput, strip=False)
    email = forms.EmailField(label="Email Address", required=True)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Passwords do not match!')
        return password_confirm

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('Email already registered.', code='email_registered')
        except User.DoesNotExist:
            return email

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        if not first_name and not last_name:
            raise forms.ValidationError('Fill out either First Name or Last Name!')
        return first_name

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Avatar', required=False)
    about = forms.CharField(max_length=2000, label='About',  required=False, widget=forms.Textarea)
    git_hub = forms.URLField(max_length=200, required=False, label='Git Hub')

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)


    def save(self, commit=True):
        user = super().save(commit=commit)
        user.profile = self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))
        if not profile.avatar:
            profile.avatar = None
        if commit:
            profile.save()
        return profile

    def clean_git_hub(self):
        git_hub = self.cleaned_data.get('git_hub')
        if "github.com" not in git_hub[:18]:
            raise ValidationError('Invalid url.', code='invalid_url')
        return git_hub

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        profile_fields = ['avatar', 'about', 'git_hub']


class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm',
                                       widget=forms.PasswordInput)
    old_password = forms.CharField(max_length=100, required=True, label='Old Password',
                                   widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password.', code='invalid_password')
        return old_password

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView

from accounts.models import Profile
from .forms import UserCreationForm, UserChangePasswordForm, UserChangeForm


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:index')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('webapp:index')
    else:
        form = UserCreationForm()
    return render(request, 'user_create.html', context={'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_files = []
        limited_files = []
        user = self.object
        for file in user.files.order_by('-created_at'):
            if file.access == 'public':
                limited_files.append(file)
            all_files.append(file)

        if self.object.pk == self.request.user.pk:
            context['files'] = all_files
        else:
            context['files'] = limited_files
        return context


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')


class UserIndexView(ListView):
    template_name = 'user_index.html'
    context_object_name = 'users'
    model = User

source/accounts/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="login_header">Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <br>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <br>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>
{% endblock %}

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Personal Profile{% endblock %}
{% block menu %}
    <nav class="navbar custom_nav navbar-expand-lg navbar-dark">
        <a class="navbar-brand" href="{% url 'webapp:index' %}">Home</a>
        <a class="new_review_btn" href="{% url 'accounts:user_detail' user_obj.pk %}">Back<span class="sr-only">(current)</span></a>
        <a class="new_review_btn" href="{% url 'accounts:user_update' user_obj.pk %}">Edit Profile<span class="sr-only">(current)</span></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>
{% endblock %}
{% block content %}
    <h1 class="main_header">Change Password for: {{ user_obj.username }}</h1>
    <div class="form_container">
        <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
            {% include 'partial/form.html' with button_text="Save" %}
        </form>
    </div>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block title %}Registration{% endblock %}
{% block content %}
        <h1 class="text-center">Registration</h1>
        <form action="{% url 'accounts:register' %}" method="post">
            {% include "partial/form.html" %}
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% csrf_token %}
{% block menu %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'webapp:index' %}" id="home_link">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <p class="nav-item text-white my-auto mr-2">{{ request.user }}</p>
                    <a class="nav-item btn btn-danger mx-2" href="{% url 'accounts:logout' %}" id="exit_link">Logout</a>
                {% else %}
                    <a class="nav-item btn btn-primary mx-2" href="{% url 'accounts:login' %}" id="enter_link">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block content %}
    <h1 class="main_header">Profile: {{ user_obj.username }}</h1>
    <p><b>First Name:</b> {{ user_obj.first_name }}</p>
    <p><b>Last Name:</b> {{ user_obj.last_name }}</p>
    <p><b>Email:</b> {{ user_obj.email }}</p>
    <hr>
    <h3 class="mt-5"><b>User Files </b></h3>
    <div class="row justify-content-center mb-5 pb-4">
        {% for file in files %}
            <div class="card border-dark mb-3 my_card" style="width: 18rem;">
                <div class="card-body">
                    <a class="card_header_link" href="{% url 'webapp:file_view' file.pk %}">
                        <h5 class="card-title">{{ file.name }}</h5>
                    </a>
                    <hr>
                    {% if file.author %}
                        <a class="card_header_link" href="{% url 'accounts:user_detail' file.author.pk %}">
                            <h5 class="card-subtitle mb-2 text-center"><b>Author: {{ file.author }}</b></h5>
                        </a>
                    {% else %}
                        <h5 class="card-subtitle mb-2 text-center"><b>Author: Anonymous</b></h5>
                    {% endif %}
                    <h5 class="card-subtitle mb-2">Published: {{ file.created_at }}</h5>
                    <hr>
                    <h5 class="card-subtitle mb-2">Access Type: {{ file.access }}</h5>
                    <h5 class="card-subtitle mb-2 text-center"><a class="btn btn-success mt-2" href="{{ file.file.url }}">Download Now</a></h5>
                </div>
            </div>
        {%endfor %}
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script type="application/javascript" src="{% static "js/detail.js" %}"></script>
{% endblock %}

source/accounts/templates/user_index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block menu %}
    <li><a class="navbar-brand" href="{% url 'accounts:user_index' %}">User List</a></li>
{#  <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#    <ul class="navbar-nav mr-auto">#}
{#      <li class="nav-item active">#}
{#        <a class="nav-link new_review_btn" href="{% url 'webapp:status_add' %}">+ Add Status <span class="sr-only">(current)</span></a>#}
{#      </li>#}
{#    </ul>#}
{#    <form class="form-inline my-2 my-lg-0">#}
{#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>#}
{#    </form>#}
{#  </div>#}

{% endblock %}
{% block content %}
    <h1 class="main_header">Users</h1>
    <hr/>
    <div class="row justify-content-center">
        {% for user in users %}
            <div class="card border-dark mb-3 my_card" style="width: 18rem;">
                {% if user.profile.avatar %}
                    <img src="{{ user.profile.avatar.url }}" width="250" height="250" alt="user picture">
                {% else %}
                    <img src="{% static "images/default-user.png" %}" width="250" height="250" alt="default avatar">
                {% endif %}
                <div class="card-body d-flex flex-column" >
                    <a class="card_header_link" href="{% url 'accounts:user_detail' user.pk %}"><h5 class="card-title card_names">{{ user.username }}</h5></a>
                    <h5 class="card-subtitle mb-2">First Name: {{ user.first_name }}</h5>
                    <h5 class="card-subtitle mb-2">Last Name: {{ user.last_name }}</h5>
                    <h5 class="card-subtitle mb-2">Email: {{ user.email }}</h5>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block footer %}
<footer class="page-footer my_footer font-small stylish-color-dark pt-4">
  <div class="container text-center text-md-left">
    <div class="row">
      <hr class="clearfix w-100 d-md-none">
      <div class="col-md-2 mx-auto">
      <hr class="clearfix w-100 d-md-none">
    </div>
  </div>
  <hr>
  <ul class="list-unstyled list-inline text-center py-2">
    <li class="list-inline-item">
      <h5 class="mb-1">Hope you are enjoying the experience</h5>
    </li>
  </ul>
  <hr>
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fab fa-google-plus-g"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fab fa-linkedin-in"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-dribbble mx-1">
        <i class="fab fa-dribbble"> </i>
      </a>
    </li>
  </ul>
  <div class="footer-copyright text-center py-3">© 2019 Created by: Mikhail Vishin</div>
</footer>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Personal Profile{% endblock %}
{% block menu %}
        {% if user_obj == request.user %}
            <a class="custom_nav_btn" href="{% url 'accounts:user_detail' user_obj.pk %}">View<span class="sr-only">(current)</span></a>
            <a class="custom_nav_btn" href="{% url 'accounts:user_change_password' user_obj.pk %}">Change Password<span class="sr-only">(current)</span></a>
        {% endif %}
{% endblock %}
{% block content %}
    <h1 class="main_header">Edit Profile {{ user_obj.username }}</h1>
    <div class="form_container">
         <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post" enctype="multipart/form-data">
            {% include 'partial/form.html' with button_text="Update" %}
         </form>
    </div>
{% endblock %}