source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view, UserDetailView, UserChangeView,\
    UserChangePasswordView, UserIndexView

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('<int:pk>/update', UserChangeView.as_view(), name='user_update'),
    path('<int:pk>/password_change', UserChangePasswordView.as_view(), name='user_change_password'),
    path('users', UserIndexView.as_view(), name='user_index'),
]

app_name = 'accounts'

source/main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace='webapp')),
    path('accounts/', include('accounts.urls', namespace='accounts'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views import IndexView, FileView, FileCreateView, FileUpdateView, FileDeleteView, AddPrivateAccess

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('file/<int:pk>/', FileView.as_view(), name='file_view'),
    path('file/add/', FileCreateView.as_view(), name='file_add'),
    path('file/<int:pk>/update/', FileUpdateView.as_view(), name='file_update'),
    path('file/<int:pk>/delete/', AddPrivateAccess.as_view(), name='file_delete'),

    path('file/add_private_user', AddPrivateAccess.as_view(), name='add_private_access')

    # path('project/<int:pk>/add-review/', ReviewForProductCreateView.as_view(), name='product_review_create'),
    # path('review/<int:pk>/update/', ReviewUpdateView.as_view(), name='review_update'),
    # path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
    ]

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

PUBLIC = 'public'
ACCESS_CHOICES = [(PUBLIC, 'Public'), ('hidden', 'Hidden'), ('private', 'Private')]


class File(models.Model):
    file = models.FileField(null=True, blank=True, upload_to='files', verbose_name='File')
    name = models.CharField(max_length=200, verbose_name='File Name')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='Author',
                               related_name='files')
    access = models.CharField(max_length=40, null=False, blank=False, verbose_name='Access', default=PUBLIC,
                              choices=ACCESS_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Date Added')
    user_access = models.ManyToManyField(User, related_name='private_files', blank=True,  verbose_name='User_Access')

    def __str__(self):
        return self.name

source/webapp/forms.py
from django import forms

from webapp.models import File


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Search')


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['created_at', 'author', 'user_access']


class AnonymousFileForm(forms.ModelForm):

    class Meta:
        model = File
        exclude = ['created_at', 'author', 'user_access', 'access']

source/webapp/views.py
from django.shortcuts import render

# Create your views here.

source/webapp/views/file_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.db.models import Q
from urllib.parse import urlencode
from webapp.forms import SimpleSearchForm, FileForm, AnonymousFileForm
from webapp.models import File


class IndexView(ListView):
    template_name = 'index.html'
    context_object_name = 'files'
    queryset = File.objects.filter(access='public')
    ordering = ['-created_at']
    paginate_by = 10
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = SimpleSearchForm(data=self.request.GET)
        self.search = None
        if self.form.is_valid():
            self.search_value = self.form.cleaned_data['search']
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(name__icontains=self.search_value)
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context


class FileView(DetailView):
    template_name = 'file.html'
    model = File


class FileCreateView(CreateView):
    form_class = AnonymousFileForm
    model = File
    template_name = 'create.html'

    def get_success_url(self):
        return reverse('webapp:file_view', kwargs={'pk': self.object.pk})

    def get_form(self, form_class=None):
        # file = self.get_file()
        if self.request.user.is_authenticated:
            form_class = FileForm
        return super(FileCreateView, self).get_form(form_class)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            self.object = form.save()
            if request.user.is_authenticated:
                self.object.author = request.user
            # else:
            #     self.object.access = 'public'
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class FileUpdateView(PermissionRequiredMixin, UpdateView):
    model = File
    template_name = 'update.html'
    form_class = FileForm
    context_object_name = 'file'
    permission_denied_message = 'Access Denied!'
    permission_required = 'webapp.change_file'

    def has_permission(self):
        file = File.objects.get(pk=self.kwargs['pk'])
        if file.author == self.request.user or super().has_permission():
            return True

    def get_form(self, form_class=None):
        file = self.get_file()
        if file.author is None or not self.request.user.is_authenticated:
            form_class = AnonymousFileForm
        return super(FileUpdateView, self).get_form(form_class)

    def get_file(self):
        file_pk = self.kwargs.get('pk')
        return get_object_or_404(File, pk=file_pk)

    def get_success_url(self):
        return reverse('webapp:file_view', kwargs={'pk': self.object.pk})


class FileDeleteView(PermissionRequiredMixin, DeleteView):
    model = File
    template_name = 'delete.html'
    context_object_name = 'photo'
    success_url = reverse_lazy('webapp:index')
    permission_denied_message = 'Access Denied!'
    permission_required = 'webapp.delete_photo'

    def has_permission(self):
        file = File.objects.get(pk=self.kwargs['pk'])
        if file.author == self.request.user or super().has_permission():
            return True

source/webapp/views/json_views.py
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.generic.base import View

from webapp.models import File


class AddPrivateAccess(View):
    def post(self, request):
        username = request.POST["username"]
        user = User.objects.get(username=username)
        file_id = request.POST["file_id"]
        file = File.objects.get(pk=file_id)
        if not user:
            return JsonResponse({'Message':"User not found"}, status=400)
        elif user in file.user_access.all():
            return JsonResponse({'Message': "User already has private access"}, status=400)
        else:
            File.user_access.add(user)
            return JsonResponse({'Message':"User now has private access to this file"}, data=request.data)

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Exam_10{% endblock %}</title>
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
            integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
{% block menu %}{% endblock %}
<div class="container my-container" id="content">
    {% block content %}{% endblock %}
</div>
{% block footer %}
{% endblock %}
{% block scripts %}
    <script src="js/jquery-3.4.1.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="application/javascript" src="{% static "js/detail.js" %}"></script>
{% endblock %}
</body>
</html>

source/webapp/templates/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Add File{% endblock %}
{% block menu %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'webapp:index'%}" id="home_link">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
            </div>
            <div class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <p class="nav-item text-white my-auto mr-2">{{ request.user }}</p>
                    <a class="nav-item btn btn-danger mx-2" href="{% url 'accounts:logout' %}" id="exit_link">Logout</a>
                {% else %}
                    <a class="nav-item btn btn-primary mx-2" href="{% url 'accounts:login' %}" id="enter_link">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}
{% block content %}
    <h1 class="main_header text-center pt-4">Add File</h1>
    <div class="form_container">
        <form class="my_form py-4" method="POST" action="{% url "webapp:file_add" %}" enctype="multipart/form-data" >
            {% include 'partial/form.html' with button_text="Create" %}
            <input type="submit" value="Upload" class="btn btn-primary">
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script type="application/javascript" src="{% static "js/detail.js" %}"></script>
{% endblock %}

source/webapp/templates/delete.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Delete Photo{% endblock %}
{% block menu %}
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'webapp:index'%}" id="home_link">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
            </div>
            <div class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <p class="nav-item text-white">Logged in as: {{ request.user }}</p>
                    <a class="nav-item btn btn-danger mx-2" href="{% url 'accounts:logout' %}" id="exit_link">Logout</a>
                {% else %}
                    <a class="nav-item btn btn-primary mx-2" href="{% url 'accounts:login' %}" id="enter_link">Login</a>
                {% endif %}/a>
            </div>
        </div>
    </nav>
{% endblock %}
{% block content %}
    <h1 class="delete_header text-center pt-4">Are you sure you want to delete this Photo?</h1>
    <div class="form_container d-flex">
        <form class="my_form mt-3 d-flex" method="POST" action="{% url "webapp:photo_delete" photo.pk %}">
            {% csrf_token %}
            <div class="d-flex justify-content-center">
                <div class="btn-group m-4">
                    <input type="submit" class="btn btn-danger my_confirm" value="Confirm Delete">
                    <a  href="{% url 'webapp:index' %}" class="cancel btn btn-success btn-lg active" role="button" aria-pressed="true">Cancel</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script type="application/javascript" src="{% static "js/detail.js" %}"></script>
{% endblock %}

source/webapp/templates/file.html
{% extends 'base.html' %}
{% load staticfiles %}
{% csrf_token %}
{% block menu %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'webapp:index' %}" id="home_link">Home</a>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated and perms.webapp.delete_file %}
                <a class="nav-item btn btn-outline-danger mx-2" href="{% url "webapp:file_delete" file.pk %}"
                   id="create_link">Delete</a>
            {% endif %}
            {% if request.user.is_authenticated and perms.webapp.change_file %}
                <a class="nav-item btn btn-outline-warning mx-2" href="{% url "webapp:file_update" file.pk %}#"
                   id="create_link">Edit</a>
            {% endif %}
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <p class="nav-item text-white my-auto mr-2">{{ request.user }}</p>
                    <a class="nav-item btn btn-danger mx-2" href="{% url 'accounts:logout' %}" id="exit_link">Logout</a>
                {% else %}
                    <a class="nav-item btn btn-primary mx-2" href="{% url 'accounts:login' %}" id="enter_link">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}
{% block title %}{{ file.name }}{% endblock %}
{% block content %}
    <h1 class="main_header text-center pt-4 mb-5"><b>File Details</b></h1>
    <div class="text-center">
        <h4 class="text-center mt-3 mb-3"><b>{{ file.name }}</b></h4>
        <hr>
        {% if file.author %}
            <a class="card_header_link" href="{% url 'accounts:user_detail' file.author.pk %}">
                <h5 class="card-subtitle mb-2 text-center">Author: <b>{{ file.author }}</b></h5>
            </a>
        {% else %}
            <h5 class="card-subtitle mb-2 text-center">Author: <b>Anonymous</b></h5>
        {% endif %}
        <h5>Access Type: <b>{{ file.access }}</b></h5>
        <h5>Date published: <b>{{ file.created_at }}</b></h5>
        {% if file.access == 'private' %}
            {% if request.user == file.author  or file in request.user.private_files.all %}
                <h5 class="card-subtitle mt-2 text-center"><a class="btn btn-success mt-4" href="{{ file.file.url }}">Download
                    Now</a></h5>
            {% endif %}
        {% else %}
            <h5 class="card-subtitle mt-2 text-center"><a class="btn btn-success mt-4" href="{{ file.file.url }}">Download
                Now</a></h5>
        {% endif %}
    </div>

    <h3 class="main_header pt-4 mb-5"><b>File Access Settings</b></h3>
    <form class="mb-4" id="private_users_form">
        <div class="form-group">
            <label for="user_input"><b>User Name</b></label>
            <input type="hidden" id="my_file_id" value="{{ file.id }}">
            <input type="text" class="form-control private_text_input w-50" id="user_input" aria-describedby="emailHelp">
            <small id="emailHelp" class="form-text text-muted">Add User you want to have private access to file.</small>
        </div>
        <button type="submit" class="btn btn-warning">Grant Access</button>
        <b><hr></b>
    </form>
    {% for user in file.user_access.all %}
        <div class="btn-group" role="group" aria-label="Basic example">
            <a class="card_header_link" href="{% url 'accounts:user_detail' user.pk %}">
                <button type="button" class="btn btn-info"><b>{{ user.username }}</b></button>
            </a>
            <button type="button" class="btn btn-danger">Delete</button>
        </div>
        <hr>


{#        <hr>#}
{#        <a class="card_header_link" href="{% url 'accounts:user_detail' user.pk %}">#}
{#            <h5><b>{{ user.username }}</b></h5>#}
{#        </a>#}
{#        <button type="button" class="btn btn-danger" id="delete_private_user">Delete</button>#}
    {% endfor %}
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static "js/detail.js" %}"></script>
{% endblock %}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block menu %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'webapp:index' %}" id="home_link">Home</a>
            <div class="navbar-nav ml-auto">
                <a class="nav-item btn btn-outline-warning" href="{% url 'webapp:file_add' %}" id="create_link">Add File</a>
            </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
                {% include 'partial/simple_search.html' %}
{#                {% if request.user.is_authenticated %}#}
{#                    <a class="nav-item btn btn-outline-warning" href="{% url 'webapp:photo_add' %}" id="create_link">Add Photo</a>#}
{#                {% endif %}#}

            </div>
            <div class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <p class="nav-item text-white my-auto mr-2">{{ request.user }}</p>
                    <a class="nav-item btn btn-danger mx-2" href="{% url 'accounts:logout' %}" id="exit_link">Logout</a>
                {% else %}
                    <a class="nav-item btn btn-primary mx-2" href="{% url 'accounts:login' %}" id="enter_link">Login</a>
                    <a class="custom_nav_btn" href="{% url 'accounts:register' %}">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <h1 class="main_header text-center pt-4">All Files</h1>
    <hr/>
    <div class="d-flex">
        <div class="pagination_block">
            {% if is_paginated %}
                {% include 'partial/pagination.html' %}
            {% endif %}
        </div>
    </div>
    <div class="row justify-content-center mb-5 pb-4">
        {% for file in files %}
            <div class="card border-dark mb-3 my_card" style="width: 18rem;">
                <div class="card-body">
                    <a class="card_header_link" href="{% url 'webapp:file_view' file.pk %}">
                        <h5 class="card-title">{{ file.name }}</h5>
                    </a>
                    <hr>
                    {% if file.author %}
                        <a class="card_header_link" href="{% url 'accounts:user_detail' file.author.pk %}">
                            <h5 class="card-subtitle mb-2 text-center"><b>Author: {{ file.author }}</b></h5>
                        </a>
                    {% else %}
                        <h5 class="card-subtitle mb-2 text-center"><b>Author: Anonymous</b></h5>
                    {% endif %}
                    <h5 class="card-subtitle mb-2">Published: {{ file.created_at }}</h5>
                    <hr>
                    <h5 class="card-subtitle mb-2">Access Type: {{ file.access }}</h5>
                    <h5 class="card-subtitle mb-2 text-center"><a class="btn btn-success mt-2" href="{{ file.file.url }}">Download Now</a></h5>
                </div>
            </div>

        {% endfor %}
    </div>
    <div class="d-flex bottom_pagination">
        <div class="pagination_block">
            {% if is_paginated %}
                {% include 'partial/pagination.html' %}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
{#    <script type="application/javascript" src="{% static "js/detail.js" %}"></script>#}
{% endblock %}

source/webapp/templates/update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Add File{% endblock %}
{% block menu %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'webapp:index'%}" id="home_link">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav ml-auto">
            </div>
            <div class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <p class="nav-item text-white my-auto mr-2">{{ request.user }}</p>
                    <a class="nav-item btn btn-danger mx-2" href="{% url 'accounts:logout' %}" id="exit_link">Logout</a>
                {% else %}
                    <a class="nav-item btn btn-primary mx-2" href="{% url 'accounts:login' %}" id="enter_link">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}
{% block content %}
    <h1 class="main_header text-center pt-4">Add File</h1>
    <div class="form_container">
        <form class="my_form py-4" method="POST" action="{% url "webapp:file_update" file.pk %}" enctype="multipart/form-data" >
            {% include 'partial/form.html' with button_text="Update" %}
            <input type="submit" value="Update" class="btn btn-primary">
        </form>
    </div>
{% endblock %}
{% block scripts %}
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script type="application/javascript" src="{% static "js/detail.js" %}"></script>
{% endblock %}